[package]
name = "Traveler"
version = "0.1.0"
edition = "2021"
categories = [ "game-engines", "gui" ]
description = "Time traveling through games in each ages"

[dependencies]
traveler_1970 = { path="crates/traveler_1970" }