[package]
name = "traveler_1970"
version = "0.0.1"
edition = "2021"
description = "Let there be 8bit art"
homepage = ""
license = "MIT"

[dependencies]
env_logger = "0.10"
log = "0.4"
sdl2 = { version = "0.36.0", features = ["ttf", "image", "mixer"] }